version: "2"
networks:
  frontend:
    driver: custom-driver-1
  backend:
    driver: custom-driver-2
services:
  nginx-proxy:
    image: nginx-vnc-cloud:latest
    #scale: 1
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
    restart: always
  serverserver-proxy:
    image: serverserver:latest
    ports:
      - "5000:5000"
    #scale: 1
    restart: always
    networks:
      - backend
  novnc:
    image: novnc:latest
    ports:
      - "6080:6080"
    #scale: 1
    restart: always
    networks:
      - backend


  