version: "2"
# networks:
#   frontend:
#     driver: custom-driver-1
#   backend:
#     driver: custom-driver-2
services:
  nginxproxy:
    image: nginx-vnc-cloud:latest
    #scale: 1
    ports:
      - "8080:80"
    # networks:
    #   - frontend
    #   - backend
    restart: always
  serverserverproxy:
    image: serverserver:latest
    ports:
      - "5000:80"
      - "5900:5900"
    #scale: 1
    restart: always
    # networks:
    #   - backend
  novnc:
    image: novnc:latest
    ports:
      - "6080:6080"
    #scale: 1
    restart: always
    # networks:
    #   - backend


  